name: drupal-outline
recipe: drupal9
config:
  webroot: drupal/web
  php: '7.4'
  xdebug: true
services:
  node:
    type: node:10
    ssl: false
    command: tail -f /dev/null
    port: 3000
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
node:
  service: node
npm:
  service: node
proxy:
  mailhog:
    - mail.drupal-outline.lndo.site
tooling:
  install:
    service: appserver
    description: "Install Drupal Core and modules."
    cmd:
      - git clone --branch 8.x-1.x git@git.drupal.org:project/outline.git && cd web/modules && ln -s ../../outline outline
      - drush -y site-install standard --account-pass admin --site-name "Drupal Outline" --db-url mysql://drupal9:drupal9@database/drupal9
      - drush -y en content_moderation, media, media_library, workflows
      - drush -y en admin_toolbar, admin_toolbar_tools, admin_toolbar_links_access_filter, admin_toolbar_search
      - drush -y en ctools, devel, graphql, paragraphs, pathauto, token
