name: drupal_outline
recipe: drupal8
services:
  appserver:
    xdebug: true
  node:
    type: node:10
    ssl: false
    command: tail -f /dev/null
    port: 3000
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
config:
  webroot: web
  php: '7.3'
  xdebug: true
tooling:
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
proxy:
  mailhog:
    - mail.isotopes.lndo.site
