name: drupal-outline
recipe: drupal9
services:
  drupaltest:
    type: mysql
    creds:
      user:  drupaltest
      password: drupaltest
      database: drupaltest
  appserver:
    webroot: web
    php: '7.4'
    xdebug: true
    config:
      php: php.ini
    run:
      - echo ''
      - echo ''
      - echo '#######################################################################################'
      - echo ''
      - echo 'One more step:'
      - echo '  Run `lando site-setup` to initialize the Drupal database and enable required modules'
      - echo ''
      - echo '#######################################################################################'
      - echo ''
      - echo ''
  node:
    type: node:10
    ssl: false
    command: tail -f /dev/null
    port: 3000
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
node:
  service: node
npm:
  service: node
proxy:
  mailhog:
    - mail.drupal-outline.lndo.site
tooling:
  testEntryDelete:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml /app/web/modules/outline/tests/src/Kernel/EntryKernelTest.php --filter='testEntryDelete'"
  site-setup:
    service: appserver
    description: "Install the Drupal Vue Outline client for development."
    cmd:
      - git clone --branch 8.x-1.x git@git.drupal.org:project/outline.git && ln -s ../../outline web/modules/outline
      - mv settings.php web/sites/default
      - mv settings.local.php web/sites/default
      - mv services.yml web/sites/default
      - drush -y site-install standard --account-pass admin --site-name "Drupal Outline" --db-url mysql://drupal9:drupal9@database/drupal9
      - drush -y en content_moderation, media, media_library, workflows
      - drush -y en admin_toolbar, admin_toolbar_tools, admin_toolbar_links_access_filter, admin_toolbar_search
      - drush -y en ctools, devel, graphql, paragraphs, pathauto, token
      - drush -y en outline, outline_graphql
      - drush cr
      - drush status
